services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_service
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tu-correo@ejemplo.com
      PGADMIN_DEFAULT_PASSWORD: tu_password_seguro
    ports:
      - "8080:80"
