spring.application.name=news-api

# Desactivar el soporte automático de Docker Compose
spring.docker.compose.enabled=false

# Configuración de conexión R2DBC para PostgreSQL en el VPS
spring.r2dbc.url=r2dbc:postgresql://161.132.48.67:5432/tumbes_de_miercoles
spring.r2dbc.username=user_wqswkhkwi8
spring.r2dbc.password=pass_gpugphwlgv2zur

# Opcional: Configuración del pool de conexiones reactivas
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20

jwt.secret=oH6VyzTGLJp5/QkTktV/Z49Ma2Gz6x5c3KHtIOH7bP4=
# Dummy Mail configuration para que JavaMailSender se instancie
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy@gmail.com
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
