openapi: 3.0.3
info:
  title: Tumbes de Miércoles API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /api/v1/auth/login:
    # Apunta a la operación de login
    $ref: './paths/user-login.yaml'
  /api/v1/users:
    # Apunta a la colección (Listar y Crear)
    $ref: './paths/users-collection.yaml'

  /api/v1/users/{id}:
    # Apunta a las operaciones individuales (Buscar por ID, Actualizar, Borrar)
    $ref: './paths/users-single.yaml'

components:
  schemas:
    UserRequest:
      $ref: './schemas/users/UserRequest.yaml'
    UserResponse:
      $ref: './schemas/users/UserResponse.yaml'

    LoginRequest:
      $ref: './schemas/login/LoginRequest.yaml'
    LoginResponse:
      $ref: './schemas/login/LoginResponse.yaml'